name: Esempio di GitHub Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setta l'access token di Mapbox come variabile d'ambiente
      run: echo "MAPBOX_ACCESS_TOKEN=${{ secrets.MAPBOX_ACCESS_TOKEN }}" >> $GITHUB_ENV

    - name: Esegui lo script JavaScript
      run: |
        npm install puppeteer
        node -e 'const puppeteer = require("puppeteer"); (async () => { const browser = await puppeteer.launch(); const page = await browser.newPage(); await page.goto("file://${{ github.workspace }}/index.html"); await page.waitForTimeout(5000); await browser.close(); })();'
